### ISSUE TITLE
Option to specify that JVM should hava JavaFX bundled

### ISSUE THREAD

**Issue by breuniga** [gradle/foojay-toolchains#28]
I'd like to specify that the downloaded JVM has JavaFX bundled (parameter `javafx_bundled` in foojay Disco API).
Is that already possible? Or easy to implement?

**Comment by brian-at-sri** [comment]
I would also like this feature. It looks like it would be easy enough to implement. Just need to add javafx_bundled=true to the query in the backend. I think the issue is there isn't an immediately obvious way to specify you want a javafx_bundled jdk through the gradle toolchain api. I think the easiest way would be to provide an alternate resolver i.e. FoojayFXToolchainResolver which we could set as the resolver class.

**Comment by jbartok** [comment]
Unfortunately, it's not that simple. This plugin would be simple to modify, as stated, but it wouldn't help because there would need to be support in Gradle for such a fine-grained toolchain selection, which is not there at the moment. Might be coming in future versions, but can't tell for now.
