### ISSUE TITLE
Provide a URL translator callback. 

### ISSUE THREAD

**Issue by yogurtearl** [gradle/foojay-toolchains#8]
If the foojay disco API returns something like this in the JSON response: `https://cdn.azul.com/zulu/bin/zulu11.56.19-ca-fx-jdk11.0.15-macosx_x64.dmg` 
I may need to translate that to `https://internal-proxy.mycorp.com/azul-cdn/zulu/bin/zulu11.56.19-ca-fx-jdk11.0.15-macosx_x64.dmg` before gradle tries to use that URI.

Please provide a plugin extenstion API that will allow me to add my own translation

Something like this: 
```kotlin
foojayToolchains {
    translateDownloadUri { uri: URI -> 
         // custom logic for translating to https://internal-proxy.mycorp.com/
         return translatedUri
    } 
}
```

**Comment by jbartok** [comment]
@yogurtearl one thing you could do to have the functionality you describe is to just reuse the logic from [FoojayApi.toUri()](https://github.com/gradle/foojay-toolchains/blob/39850bb1bd8a1a3b1c567d6021634ae6e7e6893f/foojay-resolver/src/main/kotlin/org/gradle/toolchains/foojay/FoojayApi.kt#L32) (it's at GAV coordinates `org.gradle.toolchains:foojay-resolver:0.1` in the `https://plugins.gradle.org/m2/` Maven repo) and then, based on that write your own [Toolchain Resolver Plugin](https://docs.gradle.org/current/userguide/toolchain_plugins.html), which would add the `URI` translation you need. 

I don't think we would implement the translation capability ourselves at the moment (primarily due to lack of resources). Even if we would, I think it would end up as a generic toolchain auto-provisioning feature and not specific to the Foojay resolver plugin. So, if you feel very strongly about it, then pls. file an issue on [gradle/gradle](https://github.com/gradle/gradle).
