### ISSUE TITLE
Provide both Kotlin and Groovy DSL samples in the README file

### ISSUE THREAD

**Issue by jbartok** [gradle/foojay-toolchains#9]

**Comment by StefMa** [comment]
Do we really want this? 🤔 
[Here](https://github.com/gradle/foojay-toolchains/commit/312cabcaddf8352e8d62e5db6e765b7c40f88db5) we have already an improvement so applying works for both DSLs.

The only change we could do is:
```diff
- resolverClass.set(org.gradle.toolchains.foojay.FoojayToolchainResolver::class.java)
+ resolverClass = org.gradle.toolchains.foojay.FoojayToolchainResolver
```

But since starting with [Gradle 8.2 Kotlin DSL will be the default](https://blog.gradle.org/kotlin-dsl-is-now-the-default-for-new-gradle-builds), I would say the need here is not big enough to add the Groovy DSL to the README.

What do you think?
If you think we still should add it, I'm happy to do that.
I would go with that:

---

<details open>

<summary>Kotlin DSL</summary>

```kotlin
plugins {
    id("org.gradle.toolchains.foojay-resolver") version "0.4.0"
}

toolchainManagement {
    jvm {
        javaRepositories {
            repository("foojay") {
                resolverClass.set(org.gradle.toolchains.foojay.FoojayToolchainResolver::class.java)
            }
        }
    }
}
```

</details>

<details>

<summary>Groovy DSL</summary>

```groovy
plugins {
    id("org.gradle.toolchains.foojay-resolver") version "0.4.0"
}

toolchainManagement {
    jvm {
        javaRepositories {
            repository("foojay") {
                resolverClass = org.gradle.toolchains.foojay.FoojayToolchainResolver
            }
        }
    }
}
```

</details>

**Comment by jbartok** [comment]
I would say it should still be added because, even though Kotlin is the preferred DSL, the Groovy DSL is also fully supported with no end of its life in sight.
